Feat/frontend forms feedback
elrouss/spanish-with-anna pull request #107
Opened 2023-07-05 20:13 UTC by elrouss

2023-07-07 16:37 UTC, yryryk requested changes
Нет возможности отправить второй запрос при ошибке сети или валидации на бэке (которая к тому-же разная у бэка и фронта)
![123456789](https://github.com/elrouss/spanish-with-anna/assets/108974517/f09233d9-d221-4366-ac40-f47d8352e605)

2023-07-15 08:07 UTC, elrouss commented
Поправил активирование кнопки после завершения запроса на сервер. Ошибкам с бэка будет посвящена другая ветка

2023-07-15 08:30 UTC, yryryk commented
> Также скачал npm пакет `classNames`

Ну наконец-то 😁

2023-07-15 21:11 UTC, yryryk approved these changes

2023-07-15 21:12 UTC, merged