feat: add intro adaptive 768
elrouss/spanish-with-anna pull request #110
Opened 2023-07-06 12:43 UTC by uzornakovre

2023-07-07 16:21 UTC, elrouss requested changes
Неплохо, но есть, что подправить

2023-07-07 16:21 UTC, elrouss commented on frontend/public/assets/images/into-image-main-2.png
Кристина изменила плашки в макете. Загрузишь другую картинку?

2023-07-07 16:21 UTC, elrouss commented on frontend/src/components/Intro/Intro.jsx
> +      <div className={styles.photo} />
Сделать декоративным, чтобы менять `url` картинки? Кхм... Можно, в принципе. Не буду прицепляться. Но посмотрим, чего Саша скажет. У нас демократия)

Как вариант еще можно было отслеживать разрешение экрана устройства пользователя через хук (с Next.js - это несколько специфически из-за гидратации, но реализуемо: я делал) и подменять `Image` внутри самого компонента

2023-07-07 16:21 UTC, elrouss commented on frontend/src/components/Intro/Intro.module.scss
> +  @media screen and (max-width: 1279px) {
Вынести в переменную `1280px` и сделать через `calc`

2023-07-07 16:21 UTC, elrouss commented on frontend/src/components/Intro/Intro.module.scss
> +    padding-left: 60px;
Отступы у всех секций должны меняться одинаково: обрати внимание, как сделан мой блок с преимуществами. Формула лежит в `styles -> abstracts -> variables -> wrappers`:
````
$margin-blocks-sides-formula-tablet: calc(
  $margin-blocks-sides-tablet / $media-tablet * 100%
);
````

2023-07-07 17:15 UTC, yryryk requested changes
Обрезает ветку на промежуточных разрешениях
![32456](https://github.com/elrouss/spanish-with-anna/assets/108974517/34932c0b-181a-45af-a4ed-f1596765d55e)
Блок с картинкой выходит за пределы body

2023-07-13 13:10 UTC, elrouss commented
Ждем правок

2023-07-16 01:10 UTC, uzornakovre commented on frontend/src/components/Intro/Intro.jsx
> +      <div className={styles.photo} />
Оставлю как есть)

2023-07-16 05:57 UTC, elrouss requested changes
На промежуточных разрешениях фотография висит в воздухе: должна прилипать к нижнему краю секции
<img width="264" alt="Снимок экрана 2023-07-16 в 08 53 22" src="https://github.com/elrouss/spanish-with-anna/assets/108838349/e9707027-29c9-48f8-8748-d569579637f2">

2023-07-16 05:57 UTC, elrouss commented on frontend/src/components/Intro/Intro.module.scss
> +  @media screen and (max-width: calc($media-desktop-s - 1px)) {
Проверить изменение отступа по левому краю: там сейчас и margin, и padding где-то, что приводит к изменению, отличному от других блоков

2023-07-16 14:12 UTC, elrouss approved these changes

2023-07-23 16:26 UTC, yryryk approved these changes

2023-07-23 16:32 UTC, merged