feat: add faq adaptive 768
elrouss/spanish-with-anna pull request #111
Opened 2023-07-06 13:51 UTC by uzornakovre

2023-07-07 19:48 UTC, elrouss requested changes
1) Проверить уменьшение отступов контейнера секции по сторонам по формуле, как в блоке "Преимущества обучения";
2) Отступы сверху и снизу блока не уменьшаются? Если уменьшаются, уменьшать там же, где и "Преимущества обучения";
3) При раскрытии/закрытии текста в гармошке текст двигается в процессе анимации. Это из-за добавления при открытии `padding-right: 40px`. Переделаешь текст под статичный, чтобы не рябило в глазах?

2023-07-07 19:48 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +  @media screen and (max-width: 1279px) {
Вынести в переменную

2023-07-07 19:48 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +  @media screen and (max-width: 1279px) {
Вынести в переменную

2023-07-11 22:19 UTC, uzornakovre commented
> * Проверить уменьшение отступов контейнера секции по сторонам по формуле, как в блоке "Преимущества обучения";

- там без отступов, просто выравнивание посередине, далее следует что-то менять уже на адаптиве мобильной версии.

> * Отступы сверху и снизу блока не уменьшаются? Если уменьшаются, уменьшать там же, где и "Преимущества обучения";

сверху увеличивается, но границы с твоим блоком не ясны. пока увеличил на 10px, но это уже нужно подправить когда будет собран весь проект, или ты в своем блоке.

> * При раскрытии/закрытии текста в гармошке текст двигается в процессе анимации. Это из-за добавления при открытии `padding-right: 40px`. Переделаешь текст под статичный, чтобы не рябило в глазах?

- убрал

2023-07-13 13:19 UTC, elrouss approved these changes
Обрати внимание на комментарий к смене отступов сверху и снизу блока. Получится это сделать на 1023, а не на 1279?

Аппрувлю, чтобы не терять время, но по возможности лучше поправить :)

2023-07-13 13:19 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +  @media screen and (max-width: calc($media-desktop-s - 1px)) {
У тебя получится поменять отступы сверху и снизу блока на 1023px, а не на 1279px? Нужно, чтобы у всех они менялись в одном месте.

2023-07-15 21:15 UTC, yryryk approved these changes

2023-07-15 23:12 UTC, uzornakovre commented
> Обрати внимание на комментарий к смене отступов сверху и снизу блока. Получится это сделать на 1023, а не на 1279?
> 
> Аппрувлю, чтобы не терять время, но по возможности лучше поправить :)

Поправил

2023-07-15 23:12 UTC, merged