feat: add info adaptive 768
elrouss/spanish-with-anna pull request #112
Opened 2023-07-06 15:11 UTC by uzornakovre

2023-07-07 19:38 UTC, elrouss requested changes
Паддинги сверху и снизу блока не меняются? Проверь макет и посмотри еще, на каком разрешении я меняю, чтобы у всех все было одинаково :)

2023-07-07 19:38 UTC, elrouss commented on frontend/src/components/Info/Info.module.scss
> +  @media screen and (max-width: 1279px) {
Вынести в переменную и прописать через `calc`

2023-07-07 19:38 UTC, elrouss commented on frontend/src/components/Info/Info.module.scss
> +  @media screen and (max-width: 1279px) {
Вынести в переменную и прописать через `calc`

2023-07-07 19:38 UTC, elrouss commented on frontend/src/components/Info/Info.module.scss
> +    padding-left: 60px;
Здесь должен быть динамический отступ по формуле:
````
@media screen and (max-width: calc($media-desktop - 1px)) {
    margin: 0 $margin-blocks-sides-formula-tablet;
  }
````

Поскольку тебе для слайдера нужен только для левого края, сделай по левому)

2023-07-07 19:38 UTC, elrouss commented on frontend/src/components/Info/Info.module.scss
> +  width: 100vw;
Не уверен: `100vw` обычно не рекомендуется использовать из-за скролла, который есть на Windows. Он может влиять на конечный размер. Ты проверял на Windows? Лучше тогда 100%

2023-07-07 19:38 UTC, elrouss commented on frontend/src/components/Info/Info.module.scss
> +    background: #2F2F37;
Вынести в переменную

2023-07-07 19:38 UTC, elrouss commented on frontend/src/components/Info/Info.module.scss
> +    width: 0px;
Убрать `px`

2023-07-07 19:38 UTC, elrouss commented on frontend/src/components/Info/Info.module.scss
> +  @media screen and (max-width: 1279px) {
Вынести в переменную

2023-07-07 19:38 UTC, elrouss commented on frontend/src/components/Info/Info.module.scss
> +  @media screen and (max-width: 1279px) {
Вынести в переменную

2023-07-13 13:20 UTC, elrouss commented
Ждем исправления

2023-07-15 21:27 UTC, yryryk requested changes
![345](https://github.com/elrouss/spanish-with-anna/assets/108974517/31965a9d-192c-412f-8d35-fd7c9f51f250)

2023-07-16 00:29 UTC, uzornakovre commented on frontend/src/components/Info/Info.module.scss
> +    background: #2F2F37;
Оно тут не нужно, видимо забыл поменять на transparent после копипаста) Исправлю.

2023-07-16 00:31 UTC, uzornakovre commented
> ![345](https://user-images.githubusercontent.com/108974517/253774337-31965a9d-192c-412f-8d35-fd7c9f51f250.jpg)

Видимо из-за 100vw, на маке не было видно. Исправил

2023-07-16 05:44 UTC, elrouss commented
Горизонтальный скролл 100% вылезает из-за `100vw` на ОС WIndows, поэтому его не рекомендуется использовать. У меня Mac, поэтому тоже не заметил)

2023-07-16 05:50 UTC, elrouss approved these changes

2023-07-23 16:30 UTC, yryryk approved these changes

2023-07-23 16:32 UTC, merged