feat: add translation adaptive 768
elrouss/spanish-with-anna pull request #113
Opened 2023-07-06 15:59 UTC by uzornakovre

2023-07-07 19:53 UTC, elrouss requested changes

2023-07-07 19:53 UTC, elrouss commented on frontend/src/components/ServicesTranslation/ServicesTranslation.module.scss
> +    margin-left: 60px;
Сделай отступ динамическим

2023-07-13 11:59 UTC, elrouss requested changes

2023-07-13 11:59 UTC, elrouss commented on frontend/src/components/ServicesTranslation/ServicesTranslation.module.scss
> +  @media screen and (max-width: calc($media-laptop - 1px)) {
<img width="296" alt="Снимок экрана 2023-07-13 в 14 46 02" src="https://github.com/elrouss/spanish-with-anna/assets/108838349/860b9e20-c34a-4544-8833-3e6c085c119b">

На промежуточных разрешениях вылезла плитка, соответственно на 768px не примыкает к правому краю  -> поменять margin (лучше) либо добавить `overflow: hidden` к блоху (хуже)

2023-07-15 21:31 UTC, yryryk commented on frontend/src/components/ServicesTranslation/ServicesTranslation.module.scss
> +  @media screen and (max-width: calc($media-laptop - 1px)) {
Тоже заметил

2023-07-15 21:32 UTC, yryryk approved these changes

2023-07-15 23:17 UTC, uzornakovre commented on frontend/src/components/ServicesTranslation/ServicesTranslation.module.scss
> +  @media screen and (max-width: calc($media-laptop - 1px)) {
Из-за динамического отступа вылезла вообще-то))

2023-07-15 23:18 UTC, uzornakovre commented on frontend/src/components/ServicesTranslation/ServicesTranslation.module.scss
> +  @media screen and (max-width: calc($media-laptop - 1px)) {
Сейчас исправлю

2023-07-15 23:20 UTC, uzornakovre commented on frontend/src/components/ServicesTranslation/ServicesTranslation.module.scss
> +  @media screen and (max-width: calc($media-laptop - 1px)) {
Готово

2023-07-15 23:22 UTC, uzornakovre commented on frontend/src/components/ServicesTranslation/ServicesTranslation.module.scss
> +  @media screen and (max-width: calc($media-laptop - 1px)) {
Там было дело в том, что я маргин поменял на переменную, а в формуле ширины оставил фиксированную величину. Помогло просто изменить ее на ту же переменную

2023-07-16 05:42 UTC, elrouss approved these changes

2023-07-16 10:08 UTC, merged