Feat/autorization form
elrouss/spanish-with-anna pull request #117
Opened 2023-07-12 13:29 UTC by yryryk

Вёрстка страниц регистрации и авторизации для десктопа и планшета.
По PP проверял и там есть различия с макетом в несколько пикселей, которые я исправлять не буду по причине того, что макет не симмертичен для одинаковых страниц, и эта ассимметрия проявилась при использовании одного компонента для отрисовки двух страниц.
Подключение к серверу настрою позже, чтобы не было конфликтов с ещё не смерженой веткой с обратной связью.

2023-07-12 18:21 UTC, yryryk commented
Блин, я же куст забыл 😅. Завтра доделаю.

2023-07-13 14:05 UTC, elrouss requested changes
Получился очень хороший блок кода, чистенько и аккуратно. С моей стороны только несколько мелких замечаний, которые ты сможешь быстро поправить (см. внутри). Здесь же отмечу только следующее:
1) Правильно - Authorization (переименовать)
2) На главной странице добавить переход по нажатию на кнопки на страницы регистрации/авторизации (в шапке и в блоке регистрации)
3) Оптимизированы ли изображения? Лучше использовать формат png, а не svg. Костя использовал svg, потому что у него есть тексты, которые могут превратить в пиксели при ближайшем рассмотрении. У тебя только 1 слово - Spain, и это не страшно
4) Иконку с подсказкой завернуть в кнопку (такое допустимо, согласно W3C) и добавить `aria-label` с текстом `Посмотреть подсказку к полю ввода пароля`, чтобы скринридер мог прочитать ее и ЧОВ было понятно назначение этого элемента. Кроме того, он сможет перейти на нее клавишей `Tab`;
5) Предлагаю вместе подумать над валидацией форм. Может быть, сделать ее двухфакторной? Сейчас, если через DOM убрать атрибут `disabled` у кнопки, форма становится валидной и можно отправить запрос на сервер. Предлагаю добавить еще одну проверку, когда данные попадают в функцию сабмита: если они не валидны, то будут возвращаться пользователю и отображаться в местах ошибок

2023-07-13 14:05 UTC, elrouss commented on frontend/src/components/forms/Autorization/AutorizationForms/LoginForm.jsx
> +          aria-label="Забыли пароль?"
`aria-label` можно не указывать для кнопок, внутри которых есть текст. Он требуется для скринридеров и необходим для кнопок без текста, чтобы люди с ограниченными возможностями понимали назначение кнопки без текста

2023-07-13 14:05 UTC, elrouss commented on frontend/src/components/forms/Autorization/AutorizationForms/LoginForm.jsx
> +        disabled={Boolean(Object.keys(formikLogin.errors).length)}
Кнопку предлагаю дизейблить сразу же при отрисовке страницы. Сейчас она выглядит активной и дизейблится только после нажатия.

Я использовал такое решение:
````
disabled={
          !formik.isValid ||
          formik.isSubmitting ||
          (!Object.keys(formik.touched).length &&
            formik.touched.constructor === Object)
        }
   ````

2023-07-13 14:05 UTC, elrouss commented on frontend/src/components/forms/Autorization/AutorizationForms/RegisterForm.jsx
> +        disabled={Boolean(Object.keys(formikRegister.errors).length)}
При открытии страницы кнопка не задизейблена. Предлагаю дизейблить.

Для этого можно использовать такой код:
````
disabled={
          !formik.isValid ||
          formik.isSubmitting ||
          (!Object.keys(formik.touched).length &&
            formik.touched.constructor === Object)
        }
    ````

2023-07-13 14:05 UTC, elrouss commented on frontend/src/components/forms/Autorization/FormsContainer/FormsContainer.jsx
> +            href="/"
Нужно в директории `utlis` создать объект с роутингом приложения в отдельном файле `routes`. Объект может выглядеть, например, так: https://github.com/elrouss/react-burger/blob/main/src/utils/constants.jsx. Соответственно роуты берем оттуда

2023-07-13 14:05 UTC, elrouss commented on frontend/src/components/forms/Autorization/FormsContainer/FormsContainer.jsx
> +              href="/"
Вынести в объект роутинга (см. выше)

2023-07-13 14:05 UTC, elrouss commented on frontend/src/components/forms/Autorization/FormsContainer/FormsContainer.module.scss
> +    padding: 0 calc((100vw - 768px)/(1440 - 768) * (134 - 60) + 60px) 0 calc((100vw - 768px)/(1440 - 768) * (140 - 60) + 60px);
Это не наша формула из Хабра? Можно вынести в файл `functions.scss`

2023-07-13 14:05 UTC, elrouss commented on frontend/src/components/forms/Autorization/FormsContainer/FormsContainer.module.scss
> +  background-color: #F0F9FB;
Использовать переменную `$color-main-2`

2023-07-13 14:05 UTC, elrouss commented on frontend/src/components/forms/Autorization/FormsContainer/FormsContainer.module.scss
> +    gap: calc((100vw - 1024px)/(1440 - 1024) * (170 - 70) + 70px);
Вынести в функцию

2023-07-13 14:05 UTC, elrouss commented on frontend/src/components/forms/Autorization/FormsContainer/FormsContainer.module.scss
> +    padding: 100px calc((100vw - 1024px)/(1440 - 1024) * (138 - 50) + 50px) 50px calc((100vw - 1024px)/(1440 - 1024) * (142 - 50) + 50px);
Вынести в функцию

2023-07-13 14:05 UTC, elrouss commented on frontend/src/utils/data/authorization.jsx
Что-то новенькое. Объяснишь?

2023-07-13 14:05 UTC, elrouss commented on frontend/src/assets/icons/MicroTooltipIcon.jsx
> +function MicroTooltipIcon() {
В верстке надо будет добавить `cursor: pointer` на иконку

2023-07-13 14:14 UTC, elrouss commented
И еще сейчас обратил внимание: нужно добавить псевдо-классы для стилей "Зарегистрироваться" и "Войти" в шапке

2023-11-21 18:34 UTC, elrouss approved these changes
Есть что поправить, но пока аппрувлю и вливаю

2023-11-21 18:35 UTC, merged