feat: add footer
elrouss/spanish-with-anna pull request #43
Opened 2023-06-08 19:53 UTC by AlexanderGrams

2023-06-09 06:22 UTC, elrouss requested changes
Привет!
Проделана хорошая работа. Визуально соответствует макету (на шрифты не обращаем внимание -> конфликт решим во время мерджа), использованы правильная семантика, компонент `Link`.

Есть ряд замечаний, который нужно исправить. Также уточни, пожалуйста, у Кристины, нужен ли какой-то `hover` у иконок соцсетей

2023-06-09 06:22 UTC, elrouss commented on frontend/src/components/Footer/Footer.jsx
> +            <FooterLink href="/#">Политика конфидициальности</FooterLink>
Опечатка (из макета). Исправишь в верстке, пожалуйста, и напишешь об этом Кристине?

2023-06-09 06:22 UTC, elrouss commented on frontend/src/components/Footer/Footer.jsx
> +          <div className={styles.constacts}>
Опечатка

2023-06-09 06:22 UTC, elrouss commented on frontend/src/components/Footer/Footer.jsx
> +                  <IconYoutube alt="ютуб-канал" />
Аналогично с логотипом

2023-06-09 06:22 UTC, elrouss commented on frontend/src/components/Footer/Footer.jsx
> +                  <IconTelegram alt="телеграм-канал" />
Аналогично с логотипом

2023-06-09 06:22 UTC, elrouss commented on frontend/src/components/Footer/Footer.jsx
> +          ©&#160;{new Date().getFullYear()}&#160;DesignGroup
Здесь лучше уточнить у PM: это должна быть фиксированная дата или год создания сайта

2023-06-09 06:22 UTC, elrouss commented on frontend/src/components/Footer/Footer.jsx
> +            <Link href="/#" className={styles.email}>
В `href` прописать `mailto:anyadobkes@gmail.com`, чтобы при нажатии открывался почтовый агент и можно было бы сразу отправить письмо на почту.

Можно еще добавить атрибут `lang="en"`, чтобы скринридер корректно прочитал текст

2023-06-09 06:22 UTC, elrouss commented on frontend/src/components/Footer/footer.module.scss
> +  margin: 0;
У всех ссылок в `globals` отключены отступы => можно это повторно не прописывать (здесь и ниже)

2023-06-09 06:22 UTC, elrouss commented on frontend/src/components/Footer/footer.module.scss
> +  font-family: 'Manrope', sans-serif;
Семейство должно подключаться через `var(--font-manrope)`. `sans-serif` можно не указывать, т. к. есть уже в корне.

Еще у нас есть миксин `@include renderFont`, в котором прописаны дефолтные вещи. Лучше использовать его

2023-06-09 06:22 UTC, elrouss commented on frontend/src/components/Footer/footer.module.scss
> +  @include renderFont(
Вот, а тут есть миксин)

2023-06-09 06:22 UTC, elrouss commented on frontend/src/components/FooterLink/footerLink.module.scss
> +  font-family: 'Manrope', sans-serif;
Использовать миксин

2023-06-09 06:22 UTC, elrouss commented on frontend/src/styles/abstracts/variables/colors.scss
> +$color-secondary-4: #C4C4C4;
Лучше нижний регистр: Prettier форматирует его автоматически

2023-06-09 06:56 UTC, elrouss commented on frontend/src/components/Footer/Footer.jsx
> +            <IconLogo alt="логотип" />
А еще я сейчас задумался: ты ведь передаешь `alt` как пропс в компонент и он в итоге никак не проявляется. Вообще, надо, наверное, все же достать svg-ки из компонентов, добавить обычными картинками, вставить в `Image` от Next.js, и тогда прописать `alt`.

Sorry,  c `svg` - мой просчет

2023-06-10 13:03 UTC, yryryk submitted a review, later dismissed
Bellissimo, perfecto!
Но надо переделать)
Шрифты, опечатки, aria-label.
Удачи со шрифтами, у меня только так подрубились: 
```
className={`${manrope.variable} ${raleway.variable}`}
```

2023-06-11 04:23 UTC, AlexanderGrams commented
1) У некоторых кнопок есть внутренние отступы.
В целом решение не назову плохим. Играет большую роль эффект которого хотел добиться именно ты.
Я вижу необходимость отступов для случаев, если количество кнопок увеличится или будет уменьшено разрешение, но в таких случаях на мой субъективный взгляд скорее подойдут внешние отступы. К тому же из за использования внутренних отступов есть проблема с наведением на пустое пространство, причем в данном дизайне кнопок визуально не подразумевается его использование.
Я обычно использую внешний отступ с одной нужной стороны, а последнему ребенку его убираю, подсмотрел это решение в каком-то мастер-классе, в целом достаточно популярное решение.
2) Очень смущает объявление функции closeMenu в useEffect.
В данном случае useEffect отрабатывает один раз, однако думаю лучше вынести объявление и оставить только вызов.

В целом код мне понравился, чистенько, жалко что с условиями не получилось придумать что-то по проще, конструкция действительно нагруженная, я бы рассмотрел вариант если не в упрощение, так хотя бы в сторону читабельности, она тоже важна для доработок в будущем.

2023-06-14 01:30 UTC, elrouss requested changes
Добавь, пожалуйста, открытие почтового агента при нажатии на электронную почту (остальное - мелочи) - и тогда можно аппрувить

2023-06-14 01:30 UTC, elrouss commented on frontend/src/components/Footer/Footer.jsx
> +                  aria-label="иконка, ведущий на ютуб канал"
С заглавной буквы, пожалуйста. И можно писать коротко: "Иконка - канал на YouTube

Здесь и далее

2023-06-14 01:30 UTC, elrouss commented on frontend/src/components/Footer/Footer.jsx
> +                  <IconYoutube alt="ютуб-канал" styles={styles.iconLink} />
Канал на YouTube

2023-06-14 01:30 UTC, elrouss commented on frontend/src/components/Footer/Footer.jsx
> +            <Link href="/#" className={styles.email}>
Не добавил. Также отсутствует `hover`

2023-06-14 01:30 UTC, elrouss commented on frontend/src/styles/components/icons.scss
> +  fill: #6F99A1;
Строчными буквами

2023-06-15 14:37 UTC, elrouss approved these changes

2023-06-15 14:41 UTC, merged