Feat/header
elrouss/spanish-with-anna pull request #44
Opened 2023-06-08 20:39 UTC by yryryk

2023-06-09 07:17 UTC, elrouss requested changes
Привет!
Проделана отличная работа. Визуально верстка соответствует макету, красивое появление выпадающего меню, грамотное использование семантических тегов.

Из **существенного**: обрати внимание на комментарий к логике с выпадающим меню (поиск по DOM, стили, размонтирование компонента и проч.). Вам с Сашей нужно договориться о логотипе. Также нужно добавить плавность в появлении точек в навигации: возьми анимацию из переменных.

Еще заметил такую штуку. Может привести к интересной визуализации контента на некоторых устройствах:
<img width="190" alt="Снимок экрана 2023-06-09 в 10 12 18" src="https://github.com/elrouss/spanish-with-anna/assets/108838349/36bb23a1-5bd4-418a-bc9e-c9ced42dc4e0">

2023-06-09 07:17 UTC, elrouss commented on frontend/src/components/Header/Header.jsx
> +        <nav className={styles.navigation}>
В навигацию попали кнопки регистрации и авторизации: это все же не навигация по сайту, а действие. Вытащить оттуда

2023-06-09 07:17 UTC, elrouss commented on frontend/src/styles/components/header.module.scss
> +.header {
Здесь и далее: сгруппируй, пожалуйста, свойства, согласно [стайлгайду](https://github.com/elrouss/spanish-with-anna/issues/40)

2023-06-09 07:17 UTC, elrouss commented on frontend/src/styles/components/header.module.scss
> +  z-index: 9;
Лучше давать какие-то большие значения: 100, 200, 300, 1000, 2000 и т.п.

1, 2, 3, 4, 5 - сложно потом контролировать :)

2023-06-09 07:17 UTC, elrouss commented on frontend/src/styles/components/header.module.scss
> +  font-style: normal;
Использовать миксин

2023-06-09 07:17 UTC, elrouss commented on frontend/src/styles/components/header.module.scss
> +      position: absolute;
Вот этот фрагмент повторяется несколько раз. Не хочешь его, например, вставить в плейсхолдер? Их можно подключать локально для модуля. На твое усмотрение :)

````
position: absolute;
      width: 4px;
      height: 4px;
      border-radius: 2px;
      background-color: $color-main-3;
````

2023-06-09 07:17 UTC, elrouss commented on frontend/src/styles/components/header.module.scss
> +  padding: 0;
У кнопок отключены глобально паддинги => можно убрать. Кстати, может добавишь отключение border и проч. у кнопок в глобальный сброс?

2023-06-09 07:17 UTC, elrouss commented on frontend/src/styles/components/header.module.scss
> +  border-radius: 0px 0px 20px 20px;
Убрать `px` у нулей

2023-06-09 07:17 UTC, elrouss commented on frontend/src/styles/globals.scss
> +  padding-top: 98px
Зачем это глобально?)

2023-06-09 07:54 UTC, yryryk commented on frontend/src/components/Header/Header.jsx
> +        (evt.target.id ? !(evt.target.id === 'drop-button') : true) &&
Не могу прямо так сходу согласиться, надо получше обмозговать этот момент. По идее нам же вообще не нужно чтобы хэдер перерендеривался в роутинге

2023-06-09 07:57 UTC, yryryk commented on frontend/src/components/Header/Header.jsx
> +        <nav className={styles.navigation}>
Как это не навигация? Технически это точно навигация.

2023-06-09 07:59 UTC, yryryk commented on frontend/src/styles/components/header.module.scss
> +  z-index: 9;
Думаешь у нас будет больше 10 слоёв?

2023-06-09 07:59 UTC, elrouss commented on frontend/src/components/Header/Header.jsx
> +        (evt.target.id ? !(evt.target.id === 'drop-button') : true) &&
Это настолько простой по своей сути компонент, что лишний ререндер никак не приведет к багам)

2023-06-09 08:02 UTC, yryryk commented on frontend/src/styles/components/header.module.scss
> +  border-radius: 0px 0px 20px 20px;
Блин))

2023-06-09 08:05 UTC, yryryk commented on frontend/src/styles/globals.scss
> +  padding-top: 98px
Header position fixed - он не занимает место. У нас будут страницы без него?

2023-06-09 09:04 UTC, elrouss commented on frontend/src/styles/globals.scss
> +  padding-top: 98px
Да, например, авторизация и регистрация

2023-06-09 09:46 UTC, yryryk commented on frontend/src/components/Header/Header.jsx
> +      document.querySelector('#dropDownMenuStyle').style;
Ночью делал) 
Насчёт поиска по dom - действительно надо переделать) 
Через добавление классов само собой пробовал, но не срослось. Сегодня ещё попробую - появилась пара мыслей на этот счёт.

2023-06-09 16:03 UTC, yryryk commented on frontend/src/components/Header/Header.jsx
> +      document.querySelector('#dropDownMenuStyle').style;
Блин, за 2 минуты нормально сделал)))

2023-06-09 16:31 UTC, yryryk commented on frontend/src/components/Header/Header.jsx
> +        (evt.target.id ? !(evt.target.id === 'drop-button') : true) &&
Всё таки не вижу ничего плохого в том, что нажатие на выпадающее меню приводит к его закрытию. А усложнять код для того чтобы в итоге на странице появилась маленькая некликабельная область как-то странно и бессмысленно имхо.

2023-06-09 16:32 UTC, yryryk commented on frontend/src/components/Header/Header.jsx
> +        (evt.target.id ? !(evt.target.id === 'drop-button') : true) &&
Хотя если представить ситуацию в которой пользователь промахивается при клике на ссылку в этом меню, то наверное ты прав.

2023-06-09 16:44 UTC, yryryk commented on frontend/src/styles/components/header.module.scss
> +  z-index: 9;
https://doka.guide/css/z-index/#alyona-batickaya-sovetuet

2023-06-09 17:04 UTC, elrouss commented on frontend/src/styles/components/header.module.scss
> +  z-index: 9;
Я читал о том, что как раз не стоит использовать -1, 0, 1, т. к. у них маленький шаг, сложно запомнить и, если надо будет вставить в процессе верстки между 0 и 1 какой-то новый слой, то... Ну ты понял. Можешь оставить, конечно, 9, но имей в виду мою рекомендацию. И почему, кстати, ты выбрал именно 9, а не хотя бы делящееся на 10?)

2023-06-09 17:07 UTC, elrouss commented on frontend/src/components/Header/Header.jsx
> +        (evt.target.id ? !(evt.target.id === 'drop-button') : true) &&
Именно потому, что пользователь может промахнуться. Да и в целом это выглядит как недоработка со стороны разработчиков. А код не сильно-то и усложнится)

2023-06-10 06:46 UTC, yryryk commented on frontend/src/components/Header/Header.jsx
> +import { manrope } from '@/assets/fonts/fonts';
Не подтягивает из миксина без импорта в файл.

2023-06-10 12:08 UTC, elrouss requested changes
Привет!
Все хорошо, но есть вопросы к поведению выпадающего меню. Одно точно надо поправить, а по пп. 2-3 лучше уточнить у Кристины, как она это видит.

Кроме того, не поправил тут :(
<img width="353" alt="Снимок экрана 2023-06-10 в 15 07 22" src="https://github.com/elrouss/spanish-with-anna/assets/108838349/62cd4b41-5106-45eb-9c4d-3a38d8035129">

2023-06-10 12:08 UTC, elrouss commented on frontend/src/components/Header/Header.jsx
> +                className={`${styles.dropDownMenuContainer}${
1) При клике на само выпадающее меню (не на ссылку) исчезает фокус у "Онлайн-курсы".
2) Если кликать на другие ссылки навигации ("Услуги перевода/Обо мне"), не закрывается выпадающее меню.
3) Кроме того, не исчезает точка у "Онлайн-курсы" при закрытии модального окна в случае нажатия на "Онлайн-курсы".

Уточни, пожалуйста, на всякий случай поведение менюшки у Кристины по пп. 2-3

2023-06-10 14:03 UTC, yryryk commented on frontend/src/components/Header/Header.jsx
> +                className={`${styles.dropDownMenuContainer}${
Второе исправил, остальное невоспроизводимо

2023-06-10 18:16 UTC, elrouss approved these changes
Вроде бы все нормально. Молодец! 🥇

2023-06-10 18:16 UTC, elrouss commented on frontend/src/components/Header/Header.jsx
> +                className={`${styles.dropDownMenuContainer}${
Окей, 1 и 3 - до мобилы :)

2023-06-11 04:32 UTC, AlexanderGrams commented
1) У некоторых кнопок есть внутренние отступы.
В целом решение не назову плохим. Играет большую роль эффект которого хотел добиться именно ты.
Я вижу необходимость отступов для случаев, если количество кнопок увеличится или будет уменьшено разрешение, но в таких случаях на мой субъективный взгляд скорее подойдут внешние отступы. К тому же из за использования внутренних отступов есть проблема с наведением на пустое пространство, причем в данном дизайне кнопок визуально не подразумевается его использование.
Я обычно использую внешний отступ с одной нужной стороны, а последнему ребенку его убираю, подсмотрел это решение в каком-то мастер-классе, в целом достаточно популярное решение.
2) Очень смущает объявление функции closeMenu в useEffect.
В данном случае useEffect отрабатывает один раз, однако думаю лучше вынести объявление и оставить только вызов.


В целом код мне понравился, чистенько, жалко что с условиями не получилось придумать что-то по проще, конструкция действительно нагруженная, я бы рассмотрел вариант если не в упрощение, так хотя бы в сторону читабельности, она тоже важна для доработок в будущем.

2023-06-11 07:20 UTC, merged