Feat/intro
elrouss/spanish-with-anna pull request #47
Opened 2023-06-09 10:40 UTC by uzornakovre

2023-06-10 11:16 UTC, elrouss commented on frontend/src/components/Intro/Intro.jsx
> +          Меня зовут Анна, я&nbsp;преподаватель, дипломированный переводчик и
Очень хорошо, что прогнал через типограф :)

2023-06-10 11:26 UTC, elrouss approved these changes
Привет!
Все хорошо. Буквально пара мелочей (на твое усмотрение, но для контейнера я бы все же взял переменную)

2023-06-10 11:26 UTC, elrouss commented on frontend/src/components/Intro/Intro.module.scss
> +  max-width: 1160px;
Здесь можно указать переменную `$wrapper-main-desktop`

2023-06-10 11:26 UTC, elrouss commented on frontend/src/components/Intro/Intro.module.scss
> +  display: block;
Дефолтный по умолчанию -> можно вычеркнуть

2023-06-10 11:26 UTC, elrouss commented on frontend/src/components/Intro/Intro.module.scss
> +    400,
Не сработало: нужно писать `$weight: 400`. Но вообще дефолтное для данного миксина, поэтому можно не указывать :)

2023-06-10 11:26 UTC, elrouss commented on frontend/src/components/Intro/Intro.module.scss
> +    $color-main-text-1
Цвет тоже дефолтный для миксина -> можно не указывать :)

2023-06-10 13:06 UTC, yryryk approved these changes

2023-06-10 15:14 UTC, yryryk requested changes
Увеличь, пожалуйста верхний маргин на 98px, а то хэдер перекроет часть этого блока из-за фиксированной позиции

2023-06-11 23:28 UTC, uzornakovre commented on frontend/src/components/Intro/Intro.module.scss
> +    400,
так не работает

2023-06-12 05:31 UTC, yryryk approved these changes

2023-06-12 10:52 UTC, merged