Feat/info
elrouss/spanish-with-anna pull request #50
Opened 2023-06-13 02:19 UTC by uzornakovre

2023-06-13 05:58 UTC, elrouss requested changes
Привет!
Отличная работа, но есть что поправить

2023-06-13 05:58 UTC, elrouss commented on frontend/src/components/Info/Info.jsx
> +      <InfoCard
У меня в консоли на Next.js не возникает ошибка, но, по идее, `key` также должен быть у InfoCard

2023-06-13 05:58 UTC, elrouss commented on frontend/src/components/Info/Info.module.scss
> +  margin: 150px auto;
Лучше - через `padding`. Если скролл по нажатию кнопки "Начать учиться" будет вести к этой секции, то проскроллится неправильно

2023-06-13 05:58 UTC, elrouss commented on frontend/src/components/Info/InfoCard.jsx
> +    <div className={styles.card}>
Использовать семантический тег `article`

2023-06-13 05:58 UTC, elrouss commented on frontend/src/components/Info/InfoCard.jsx
> +        alt={`Изображение ${title}`}
В `alt` не используем слова "Изображение", "Фотография", "Снимок"

2023-06-13 05:58 UTC, elrouss commented on frontend/src/components/Info/InfoCard.jsx
> +        style={{ objectFit: 'cover' }}
Прописать в `className`. По идее, можно жестко не задавать размеры в `Image`: есть какое-то свойство, которое растягивает по размеру контейнера (возможно, его ты и имел в виду тут)

2023-06-13 05:58 UTC, elrouss commented on frontend/src/components/Info/InfoCard.jsx
> +      {descriptions}
В верстке это должен быть один `p`, а не 2 (задать неразрывные пробелы через юникод. Текст должен не обязательно встать, как в макете: я предупредил Кристину, что Фигма и браузер считают по-разному

2023-06-13 05:58 UTC, elrouss commented on frontend/src/components/Info/InfoCard.jsx
> +  image: PropTypes.object.isRequired,
Array и Object - описать так, как я привел пример на скриншоте в чате (должно быть расписано каждое поле)

2023-06-13 05:58 UTC, elrouss commented on frontend/src/utils/data/INFO_CARDS.jsx
> +    description: ['Интерактивные занятия ', 'в мини-группах до 4-х человек'],
Зачем через массив? Сделай обычный текстом, добавь юникод для неразрывных пробелов, в карточке - ограничить максимальную ширину параграфа

2023-06-13 05:58 UTC, elrouss commented on frontend/src/utils/data/INFO_CARDS.jsx
> +    _id: '0001',
Я давал без нулей: просто 1, 2, 3, 4, 5... А при создании ключа делаю так: `info-course-${_id}`. Вроде есть еще какой-то генератор таких id, надо бы глянуть

2023-06-13 05:58 UTC, elrouss commented on frontend/src/utils/data/INFO_CARDS.jsx
> +const INFO_CARDS = [
При описании `PropTypes` должно быть что-то типа:
````
arrayof(PropTypes.shape({_id: PropTypes.string.isRequired, ...}).isRequired).isRequired
````

2023-06-14 16:11 UTC, elrouss approved these changes
Привет!
Поправь только в одном месте с `key` и вроде можно аппрувить)

2023-06-14 16:11 UTC, elrouss commented on frontend/src/components/Info/Info.jsx
> +      <InfoCard
Ключ у каждого элемента должен быть разным. Я делаю так: `infoItem-${_id}`, `infoCard-${_id}`

2023-06-14 16:21 UTC, yryryk approved these changes
Всё отлично)

2023-06-14 19:57 UTC, merged