feat: mark up section benefits on desktop Closes #32
elrouss/spanish-with-anna pull request #51
Opened 2023-06-13 17:21 UTC by elrouss

FEAT:
1) Created section benefits on desktop (1440px+);
- svgs are optimized
- checked with Pixel Perfect
- checked with W3C validator

2023-06-14 14:31 UTC, uzornakovre approved these changes
Отличная работа!

2023-06-14 14:31 UTC, uzornakovre commented on frontend/src/utils/data/studyingBenefits.jsx
> +    text: 'С\u00A0первых уроков ставлю и\u00A0корректирую произношение, чтобы вас всегда понимали иностранцы',
Переносы строк в некоторых карточках не совпадают макету, такая же проблема была у меня. Это не значительно, но единственное на что я обратил внимание.

2023-06-14 14:34 UTC, uzornakovre commented on frontend/src/utils/data/studyingBenefits.jsx
> +    text: 'С\u00A0первых уроков ставлю и\u00A0корректирую произношение, чтобы вас всегда понимали иностранцы',
Возможно и не стоит заморачиваться с ними, так как мы еще будет делать адаптив, и там формат может меняться

2023-06-14 15:34 UTC, elrouss commented on frontend/src/utils/data/studyingBenefits.jsx
> +    text: 'С\u00A0первых уроков ставлю и\u00A0корректирую произношение, чтобы вас всегда понимали иностранцы',
Да, я не заморачивался с этим и предупредил Кристину. Там из-за различной ширины контента в каждом из блоков: я выбрал такую ширину, чтобы совпадало количество строчек. Контент может меняться, слова добавляться/удаляться/переноситься и мы не обязаны в случае с текстами делать точь-в-точь :)

2023-06-14 17:04 UTC, yryryk requested changes
Хорошо свёрстаный блок. Но с svg лучше разобраться, так и код проще станет и взаимозаменяемость появится. Я считаю, что то как сейчас - это не дело.

2023-06-14 17:07 UTC, elrouss commented on frontend/src/components/StudyingBenefits/StudyingBenefits.module.scss
> +  position: absolute;
Left может стать right, а right может стать left: поэтому лучше что-то general)

2023-06-14 17:08 UTC, elrouss commented on frontend/src/components/StudyingBenefits/StudyingBenefits.module.scss
> +
Я подстроился под Pixel Perfect: там нужно вносить коррективы в макет

2023-06-14 17:23 UTC, yryryk commented on frontend/src/components/StudyingBenefits/StudyingBenefits.module.scss
> +  position: absolute;
Ну block-1 и block-2 тоже такое себе

2023-06-14 17:24 UTC, elrouss commented on frontend/src/components/StudyingBenefits/StudyingBenefits.module.scss
> +  position: absolute;
Убедил)

2023-06-15 06:24 UTC, yryryk approved these changes

2023-06-15 06:32 UTC, merged