Feat/frontend layout desktop reviews
elrouss/spanish-with-anna pull request #61
Opened 2023-06-17 11:11 UTC by elrouss

FEAT:
1) Created carousel with randomized reviews, which are additional opened with a modal window;

FIX:
1) Added rules to eslint to disable errors

2023-06-17 23:49 UTC, uzornakovre approved these changes
Классная карусель, не пользовался данной библиотекой, так что не знаю, к чему придраться)

2023-06-17 23:49 UTC, uzornakovre commented on frontend/src/assets/fonts/fonts.jsx
> +  weight: ['400', '700'],
Что это меняет?

2023-06-17 23:49 UTC, uzornakovre commented on frontend/src/components/ModalOverlay/ModalOverlay.module.scss
> +  z-index: 1000;
Где-то слышал, что лучше не использовать большие числа, а придерживаться очередности, 1-2-3-4 и тд.

2023-06-17 23:53 UTC, elrouss commented on frontend/src/components/ModalOverlay/ModalOverlay.module.scss
> +  z-index: 1000;
Я, наоборот, несколько раз слышал рекомендации, что лучше использовать большие числа: 100, 200, 300 - не придерживаясь очередности в 1 шаг. Мне кажется, что об этом говорил Витя Малий. Также точно рассказывали в RS School.

Мы обсуждали это с Сашей в коммите его шапки, но он остался на своем варианте в 1, 2, 3 и проч. :)

2023-06-17 23:55 UTC, uzornakovre commented on frontend/src/components/ModalOverlay/ModalOverlay.module.scss
> +  z-index: 1000;
Не вопрос)

2023-06-17 23:58 UTC, elrouss commented on frontend/src/assets/fonts/fonts.jsx
> +  weight: ['400', '700'],
В карточке слайда карусели есть шрифт Manrope с весом 700 ("Читать полностью"), который не отмечен в UI Kit: для подключения нужно добавить такую жирность в массив google fonts

2023-06-18 00:04 UTC, elrouss commented on frontend/src/components/ModalOverlay/ModalOverlay.module.scss
> +  z-index: 1000;
Кстати, поскольку это модальное окно и оно точно должно быть выше всех элементов, можно было использовать значение `9999`: так по крайней мере пишут в рекомендациях :D

2023-06-18 14:40 UTC, yryryk commented on frontend/src/components/ModalOverlay/ModalOverlay.module.scss
> +  z-index: 1000;
-"Где-то слышал, что лучше не использовать большие числа, а придерживаться очередности, 1-2-3-4 и тд"
- Вот и я тоже)

2023-06-18 15:32 UTC, yryryk commented on frontend/src/components/ModalOverlay/ModalOverlay.module.scss
> +  z-index: 1000;
Ответ ChatGPT:

Конкретный диапазон значений z-index зависит от конкретной ситуации и требований проекта. Однако, в большинстве случаев рекомендуется следовать этим общим рекомендациям:

Используйте относительно небольшие значения z-index, чтобы избежать потенциальных проблем с производительностью и перекрытием элементов.
Избегайте использования огромных значений z-index, так как это может привести к сложностям при управлении порядком наложения элементов.
Если вам нужно управлять порядком наложения только нескольких элементов, можно использовать небольшие положительные или отрицательные значения z-index, чтобы создать ясную и легко управляемую иерархию наложения.
Если у вас есть большое количество элементов, которые должны быть упорядочены по z-index, рассмотрите возможность использования других техник, таких как изменение порядка элементов в HTML или использование отдельных контейнеров с определенными z-index значениями.
В итоге, выбор диапазона значений z-index зависит от конкретных требований проекта и необходимости управления порядком наложения элементов.

2023-06-18 15:39 UTC, elrouss commented on frontend/src/components/ModalOverlay/ModalOverlay.module.scss
> +  z-index: 1000;
https://www.smashingmagazine.com/2021/02/css-z-index-large-projects/ - интересная статья об организации z-index в проекте. Мне понравился вариант с вынесением в один файл с переменными, чтобы не было магических чисел и мы в принципе знали, какие z-index есть у нас в проекте во избежание конфликтов наложения слоев :)

https://stackoverflow.com/questions/60133833/why-do-developers-use-high-z-index-values - и Stack Overflow

2023-06-18 19:46 UTC, yryryk requested changes
В целом очень хорошо

2023-06-18 19:46 UTC, yryryk commented on frontend/src/components/ModalOverlay/ModalOverlay.jsx
> +  return isMounted && modalRef.current
Вместе рождаются:
  ```
  useEffect(() => {
    modalRef.current = document.querySelector('#modals');

    setIsMounted(true);
  }, []);
  ```
  Вместе живут:
  ` isMounted && modalRef.current`
  Однояйцевые близнецы какие-то)
  Я удалил  isMounted и ожидаемо ничего не изменилось.
  На мой взгляд оно здесь лишнее потому что ни на что не влияет.

2023-06-18 20:10 UTC, elrouss commented on frontend/src/components/ModalOverlay/ModalOverlay.jsx
> +  return isMounted && modalRef.current
Согласен, он здесь не нужен. Удалил

2023-06-18 20:13 UTC, yryryk approved these changes

2023-06-18 20:18 UTC, merged