Feat/faq
elrouss/spanish-with-anna pull request #67
Opened 2023-06-21 13:48 UTC by uzornakovre

2023-06-21 17:25 UTC, yryryk requested changes
В целом неплохо но:
- Отсутствует анимация на элементах кнопок, ссылок и вообще
- Возможно при раскрытии фака стоило бы сделать автоматическое закрытие всех остальных факов, но это скорее вопрос к ПМ или к дизайнеру

2023-06-21 17:25 UTC, yryryk commented on frontend/src/components/FAQ/Question.jsx
> +          isAnswerVisible && styles.accordionItemHead_active
Здесь и далее если дополнительный стиль не активен, то в браузере это отображается как "false"
```class="FAQ_accordionItemHead__rlEPo false" ```
Чтобы этого избежать можно сделать через тернарник:
```condition ? "someClassName" : ""```
Или по формуле:
```condition && "someClassName" || ""```

2023-06-21 17:25 UTC, yryryk commented on frontend/src/components/FAQ/Question.jsx
> +          className={`${styles.arrowDown} ${isAnswerVisible && styles.arrowUp}`}
-

2023-06-21 17:25 UTC, yryryk commented on frontend/src/components/FAQ/Question.jsx
> +          isAnswerVisible && styles.accordionItemContent_active
-

2023-06-21 17:42 UTC, elrouss requested changes
Проделана большая работа, но есть серьезные недочеты.

Главный - в button нельзя вставлять `h` (ошибка валидации). Попробуй `button` заменить на `div` и пропиши ему обязательно атрибут `role="button" (и вроде еще нужен aria-label)` - это стандарт w3c.

<img width="1137" alt="Снимок экрана 2023-06-21 в 20 37 44" src="https://github.com/elrouss/spanish-with-anna/assets/108838349/0dc45e2e-fecd-4a03-b431-66341ff39c5a">

Также сделать плавные анимации, вставить в БД реальные ответы на вопросы (есть в макете), добавить верхний отступ блоку

2023-06-21 17:42 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.jsx
> +          <button className={styles.askButton} type="button">
Добавить плавную анимацию для всех состояний

2023-06-21 17:42 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +  z-index: 1000;
Ахахах) кто мне говорил о 1000?)

2023-06-21 17:42 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +.accordion {
У аккордеона должна быть плавная анимация

2023-06-21 17:42 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +  background-image: url('../../../public/assets/icons/tile-5.svg'), url('../../../public/assets/icons/tile-6.svg');
Не знал, что там можно делать

2023-06-21 17:42 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +  position: absolute;
Я бы кнопку засунул в общий контент центрального контейнера и сдвинул вниз с помощью relative/transform-y. Было бы меньше кода

2023-06-21 17:42 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +    $family: var(--font-manrope),
дефолтный шрифт - выкинуть

2023-06-21 17:42 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +.decorationQuestionIcon {
Аналогично с кнопкой "Задать вопрос": сделал бы по-другому -> было бы, наверное, чуть меньше кода.

2023-06-21 17:42 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +  background-image: url('../../../public/assets/icons/question.svg');
Можно одной строчкой: `background: url center no-repeat` (посмотри, на какую позицию цвет ставится

2023-06-21 17:42 UTC, elrouss commented on frontend/src/utils/data/FAQ_DATA.jsx
> +      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Alias, earum sit hic repellat omnis aspernatur delectus perspiciatis voluptatibus laudantium exercitationem suscipit adipisci ipsum ma
В макете есть ответы на все вопросы (вверх справа). Прогнать через типограф, вставить в юникод и закинуть сюда

2023-06-21 17:42 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +.arrowDown {
Сделать красивую анимацию для стрелки

2023-06-21 17:42 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +.container {
Добавить верхний паддинг блоку: вроде бы `75px`. Отмечал этот момент в макете

2023-06-21 18:25 UTC, uzornakovre commented on frontend/src/components/FAQ/FAQ.jsx
> +  const questions = FAQ_DATA.map((q) => (
Не, мне ревьюеры всегда так советовали делать. да и так визуально лучше

2023-06-21 18:29 UTC, uzornakovre commented on frontend/src/components/FAQ/FAQ.module.scss
> +  z-index: 1000;
ну ты сказал что все равно, вот и результат)

2023-06-21 18:30 UTC, uzornakovre commented on frontend/src/components/FAQ/FAQ.module.scss
> +  position: absolute;
Так проще выровнять надпись посередине, не мешают другие элементы

2023-06-21 18:31 UTC, uzornakovre commented on frontend/src/components/FAQ/FAQ.module.scss
> +.decorationQuestionIcon {
Это тоже можно оставить, не влияет думаю никак, и ничто не мешает выровнять надпись по центру

2023-06-21 18:32 UTC, uzornakovre commented on frontend/src/components/FAQ/FAQ.module.scss
> +  background-image: url('../../../public/assets/icons/question.svg');
по мне так в несколько строк проще воспринимать код, нежели в одной строчке

2023-06-21 19:13 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.jsx
> +  const questions = FAQ_DATA.map((q) => (
Ну не знаю, я не сразу понял, где искать

2023-06-21 19:14 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +  z-index: 1000;
Учти, что у модалы тоже 1000, а тут будет модала с feedback) но ладно ,все равно все перенесу в переменные))

2023-06-22 19:31 UTC, elrouss requested changes
Привет!
Проделал большую работу, значительно улучшил код. Но осталась пара недочетов, которые хотелось бы поправить:
1) Анимация стрелки: предлагаю поворачивать не на 540deg, а на 180deg + замедлить скорость до 0.4s - тогда нет ощущения головокружения и тошноты (у пользователей могут проблемы с вестибулярным аппаратом);
2) Резко исчезает и появляется текст - нужно бы поправить (возможный пример кинул, можешь самостоятельно поискать еще другие)

2023-06-22 19:31 UTC, elrouss commented on frontend/src/components/FAQ/FAQ.module.scss
> +.accordion {
Молодец, сделал плавную анимацию, но не нравится резкое появление/исчезновение текста. Доделаешь?

https://mozharov-sergey.github.io/hackathon-YandexPracticum-HR/ - у них сделано неплохо появление, но не нравится анимация

2023-06-23 07:44 UTC, yryryk approved these changes

2023-06-23 10:45 UTC, elrouss approved these changes

2023-06-23 10:46 UTC, merged