feat: add CustomField and structure to execute
elrouss/spanish-with-anna pull request #74
Opened 2023-06-24 20:17 UTC by yryryk

For review - the CustomField block, the rest so that you can run and test it

2023-06-25 06:12 UTC, elrouss requested changes
Проделана большая работа (всегда сложно вынести что-то типовое в проекте), очень неплохая библиотека, которая, действительно, облегчает жизнь. Покрыл ревью комментариями: жду feedback :)

2023-06-25 06:12 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +    errors: PropTypes.shape({}).isRequired,
PropTypes съел такой вариант и аналогичный ниже?

2023-06-25 06:12 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
Обрати внимание, что в поле пароля должен быть еще отрисован глазик в 2 состояниях. Предлагаю его отрисовать в кастомном инпуте сразу же, поставить на вход props, например `isEyeRequired` (по умолчанию равен `false`) и отрисовывать, если в пропсах передается флаг `true`. Только нужно проследить, чтобы при большом наборе символов пароль не заезжал на глазик

2023-06-25 06:36 UTC, yryryk commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +        id={`${parentName}-${name}`}
- styleguide 👍

- Ну props составной же получается, и вряд ли у нас тут будут проблемы если так и оставить, зато примерно понятно что именно лучше написать для единообразия кода и избегания коллизий

2023-06-25 06:38 UTC, yryryk commented on frontend/src/components/forms/CustomField/CustomField.jsx
Да, конечно

2023-06-25 06:43 UTC, yryryk commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +    errors: PropTypes.shape({}).isRequired,
Никаких ошибок не было нигде, А что там написать, если в объекте нет постоянной структуры? Просто на object линтер ругается.

2023-06-25 06:55 UTC, yryryk commented on frontend/src/components/forms/yapSchemas/yapSchemas.js
Я как-то так это вижу
![333](https://github.com/elrouss/spanish-with-anna/assets/108974517/1cd93e99-5858-4bbd-9b29-1e272eb4b53a)

2023-06-25 06:56 UTC, yryryk commented on frontend/src/components/forms/yapSchemas/yapSchemas.js
![444](https://github.com/elrouss/spanish-with-anna/assets/108974517/4bd828d0-b09a-4edd-ad09-0809f25fcd96)

2023-06-25 07:02 UTC, yryryk commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +        type={name}
``` CustomField({ formik, type, parentName, placeholder })
в смысле так?

2023-06-25 07:16 UTC, yryryk commented on frontend/src/components/forms/CustomField/CustomField.jsx
Да, я вчера об этом думал но мне показалась хорошей идея не перегружать этот компонент, а сделать отдельный. Но с другой стороны делать отдельный компонент ради какого-то глазика - это бред. В общем утро открыло мне глаза и  я теперь тоже думаю, что надо сделать всё в кастомном компоненте.

2023-06-25 08:05 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +        id={`${parentName}-${name}`}
Я, наоборот, не сразу понял, что за `name` и `parentName`: подумал при беглом просмотре, что требуются имя и фамилия пользователя (и затем - а зачем нам фамилия, если не прописано в ТЗ?). Нужно четко указывать, что требуется передать в input в качестве пропсов `id` и `type`. Тогда понятно, для чего это нужно

2023-06-25 08:08 UTC, yryryk commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +        type={name}
А, ну да, это же разное - туплю

2023-06-25 08:09 UTC, elrouss commented on frontend/src/components/forms/yapSchemas/yapSchemas.js
Я тоже так вижу: тогда добавишь в код валидацию для email, name, password, согласно ТЗ? Собственно, они должны быть универсальными, т. к. такая валидация в 3 формах (вкл. email и name в feedback), а также в ЛК.  RegExp напишешь? Телефон я добавлю уже сам, когда определимся с Кристиной

2023-06-25 08:10 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +        type={name}
В итоге должно быть так: `{ formik, id, type, placeholder }`

2023-06-25 08:11 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +    errors: PropTypes.shape({}).isRequired,
Саша в очередной раз хакнул систему 👯

2023-06-25 08:19 UTC, yryryk commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +        id={`${parentName}-${name}`}
```parentNameForId```

2023-06-25 08:23 UTC, yryryk commented on frontend/src/components/forms/CustomField/CustomField.jsx
Я уже вставлял button в input, но не нативно, а через абсолютное позиционирование

2023-06-25 08:44 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
Соответствует стандарту W3C?

2023-06-26 20:16 UTC, elrouss requested changes
Сделано классно, молодец! Но есть пара моментов, которые, я думаю, улучшили бы код кастомного инпута и сделали его проще и более читаемым

2023-06-26 20:16 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +  const [isPassword, setIsPassword] = useState(false);
Можно сделать гораздо проще: ввести дополнительный флаг для глаза в виде пропса (напр., `isEyeRender` или что-то вроде того (нейтральный нейминг, вдруг понадобится где-то еще; по умолчанию - `false`, т.е. `isEyeRender = false`)). Идет проверка этого пропса и соответственно отрисовывается глаз. В таком случае не нужны ни дополнительный стейт, ни эффект. При необходимости отрисовки просто пропсом пишешь `isEyeRender` (и даже не надо `isEyeRender={true}`, т. к. React автоматически интепретирует это булевым значением) + код станет короче

2023-06-26 20:16 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +  useEffect(() => {
Прокомментировал выше

2023-06-26 20:16 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +          ref={inputRef}
`ref`- лучше под `id`

2023-06-26 20:16 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +            aria-label="Посмотреть пароль"
`Посмотреть/скрыть пароль` (а идеальный вариант - менять глагол в зависимости от стейта отрисованного глаза)

2023-06-26 20:16 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
Также обрати внимание, что при клике на глаз мелькает красный border у инпута (надо бы убрать)

2023-06-26 20:16 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +      <span className={styles.error}>
В случае с паролем (текст ошибки - на 2 строки) -> прыгает кнопка

2023-06-27 11:09 UTC, yryryk commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +  const [isPassword, setIsPassword] = useState(false);
Я против такого подхода в данном случае. 
Там в так или иначе остаётся стейт, меняющийся от нажатия на глаз и перерисовки будут, другое дело, что там перерисовывать то особо нечего.
Зато меньше пропсов в собранной форме, а если форм и инпутов много, то и дополнительных пропсов в сумме дофига будет. К тому-же мой вариант исключает возможность добавить глаз туда где его быть не должно, что тоже не плохо. 
А также я за автоматизацию и тут это вполне уместно.

2023-06-27 11:18 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +  const [isPassword, setIsPassword] = useState(false);
Пример кастомного инпута с пропсами в Яндексе. По сути, это как мы подключаем любую библиотеку, где есть какие-то объекты настройки, которых может быть ОЧЕНЬ много и которые прокидываются в виде пропсов (те же слайдеры, например). В данном случае мы создаем свой кастомный элемент и он становится универсальным.  Глаз в теории может появиться, где угодно

<img width="1135" alt="Снимок экрана 2023-06-27 в 14 15 15" src="https://github.com/elrouss/spanish-with-anna/assets/108838349/e88b7d35-7419-4033-9325-96922072b07e">

2023-06-27 11:20 UTC, yryryk commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +  const [isPassword, setIsPassword] = useState(false);
Не вижу тут про пса для глаза))

2023-06-27 11:23 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +  const [isPassword, setIsPassword] = useState(false);
Они вынесли `inpu`t под пароль в отдельный. А так все допустимые иконки (глаз - это иконка) в пропсе `icon`. В нашей кейсе предлагаю оставить тут. Ну не вредничай: потом еще карандаш какой-нибудь появится, или замок :))

<img width="561" alt="Снимок экрана 2023-06-27 в 14 22 58" src="https://github.com/elrouss/spanish-with-anna/assets/108838349/f2f75ca1-3fe9-4672-b9e8-da5590858e08">

2023-06-27 11:25 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +  const [isPassword, setIsPassword] = useState(false);
Можем даже Кристине сразу выставить условие, чтобы иконки в личном кабинете ставила не рядом с инпутами, а также внутри них :))

2023-06-27 11:28 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +  const [isPassword, setIsPassword] = useState(false);
Тот же Свайпер: аналогичный принцип

<img width="499" alt="Снимок экрана 2023-06-27 в 14 28 06" src="https://github.com/elrouss/spanish-with-anna/assets/108838349/43b5a318-09ad-4473-8083-f1c18371114e">

2023-06-27 11:31 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +  const [isPassword, setIsPassword] = useState(false);
То есть мы можем сделать пропс `icon`, куда передавать текстовое содержание `eyeIcon`. Затем, когда у нас будет какой-нибудь карандаш, то допишем логику и нужно будет строкой передавать просто `editIcon` и т.д.

2023-06-27 11:32 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +  const [isPassword, setIsPassword] = useState(false);
Стили и проч. все уже будет готово 🥇

2023-06-27 11:34 UTC, elrouss commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +  const [isPassword, setIsPassword] = useState(false);
У тебя же получилось сделать в одном и это выглядит и работает вроде нормально. Осталось только на пропс переделать и будет огонь: доверься моему чутью :)

2023-06-27 14:42 UTC, yryryk commented on frontend/src/components/forms/CustomField/CustomField.jsx
> +  const [isPassword, setIsPassword] = useState(false);
Я уберу useState и useEffect, лишний пропс тут тоже не понадобится)

2023-06-27 20:38 UTC, elrouss approved these changes
Вроде нормально. Посмотрим, как расширится компонент в будущем

2023-06-28 06:28 UTC, merged